version: "3.7"
services:
  db:
    image: postgres:15.1
    restart: always
    container_name: ds_db
    environment:
      POSTGRES_DB: ds
      POSTGRES_USER: ds
      POSTGRES_PASSWORD: ds
    ports:
      - "5432:5432"
    volumes:
      - type: volume
        source: ds-db-volume
        target: /var/lib/postgresql/data      
    networks:
      - ds_network
  
  app:
    build: .
    container_name: ds_app
    ports:
      - "3000:3000"
      - "443:443"
    depends_on:
      - db
    environment:
      DB_DATABASE: ds
      DB_USERNAME: ds
      DB_PASSWORD: ds
      DB_HOST: db
      RAILS_ENV: production
      RAILS_SERVE_STATIC_FILES: 'true'
      RAILS_LOG_TO_STDOUT: 'true'
    networks:
      - ds_network

networks:
  ds_network:
      name: ds_network
      driver: bridge

volumes:
  ds-db-volume: