name: CI of biblio-num
on:
  workflow_dispatch:

jobs:
  mirror:
    name: Sync repo with Cloud Pi Native
    runs-on: ubuntu-latest
    steps:
      - name: Checks-out repository
        uses: actions/checkout@v3
      - name: Send a sync request to DSO api
        run: |
          sh script-mirror.sh \
            -g ${{ secrets.GITLAB_TRIGGER_TOKEN }} \
            -k ${{ secrets.CONSUMER_KEY }} \
            -s ${{ secrets.CONSUMER_SECRET }}
